baseURL = "http://blog.i.3fx.ch"
languageCode = "en-us"
title = "3fx.ch"

assetDir = "static"

pygmentsUseClasses = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 0
