baseURL = "https://blog.bfiedler.ch"
languageCode = "en-us"
title = "Ben's Site"

assetDir = "static"

pygmentsUseClasses = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 0
