baseURL = "https://blog.3fx.ch"
languageCode = "en-us"
title = "blog.3fx.ch"

pygmentsUseClasses = true

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 0
